# SPDX-FileCopyrightText: © 2026 Visiosto oy <visiosto@visiosto.fi>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: ci

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - uses: astral-sh/setup-uv@v7.6.0
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run build
